FROM tomcat:8
# take a war file and copy the same to tomacat
WORKDIR /usr/local/tomcat/webapps/myapp/
COPY /var/lib/jenkins/workspace/docker-app/target/mvn-hello-world  /usr/local/tomcat/webapps/mvn-hello-world.war

