FROM tomcat:8
# take a war file and copy the same to tomacat
RUN run -it \
    -p 8080:8080 \
    -v $(pwd)/target/mvn-hello-world.war:/usr/local/tomcat/webapps/mvn-hello-world.war \
    tomcat
